spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bank
    driver-class-name: org.h2.Driver
    username: sa
    platform: org.hibernate.dialect.h2dialect
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  devtools:
    restart:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 6b0e8100ce2d0c8f9694
            client-secret: 4ad29e514cc61f6f561c46a18815bddf55f6b661
            scope:
              - user:email
              - read:user
server:
  port: 9000
app:
  auth:
    tokenSecret: secret



