spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/cJnfyBdW9T
    driver-class-name: com.mysql.jdbc.Driver
    username: cJnfyBdW9T
    password: lDyVhUKz7F
server:
  port: 9000

